# Generated by Django 5.1.4 on 2025-02-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_pub', models.BooleanField(default=True)),
            ],
        ),
    ]
